//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBDiff.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBDiff.Test.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE TestConstraintFKRemoveTable1
        ///GO
        ///
        ///ALTER TABLE [dbo].[Child] DROP CONSTRAINT [FK_Child_Parent]
        ///GO
        ///ALTER TABLE [dbo].[ChildChild] DROP CONSTRAINT [FK_ChildChild_Child]
        ///GO
        ///ALTER TABLE [dbo].[Child] DROP CONSTRAINT [PK_Child]
        ///GO
        ///DROP TABLE [dbo].[ChildChild]
        ///GO
        ///DROP TABLE [dbo].[Parent]
        ///GO
        ///CREATE TABLE [dbo].[TempChild]
        ///(
        ///	[ID] [int] IDENTITY (2,2) NOT NULL,
        ///	[ParentId] [int] NOT NULL,
        ///	[Campo2] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
        ///	[Campo3] AS ([Campo2]+&apos;Hola&apos;),
        ///) ON [PRI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestConstraintFKRemove {
            get {
                return ResourceManager.GetString("TestConstraintFKRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE TestConstraintFKTree1
        ///GO
        ///
        ///ALTER TABLE [dbo].[Tabla2] DROP CONSTRAINT [FK_Tabla2_Tabla3]
        ///GO
        ///ALTER TABLE [dbo].[Tabla4] DROP CONSTRAINT [FK_Tabla4_Tabla2]
        ///GO
        ///ALTER TABLE [dbo].[Table7] DROP CONSTRAINT [FK_Table7_Tabla2]
        ///GO
        ///ALTER TABLE [dbo].[Tabla5] DROP CONSTRAINT [FK_Tabla5_Tabla6]
        ///GO
        ///ALTER TABLE [dbo].[Tabla1] DROP CONSTRAINT [FK_Tabla1_Tabla2]
        ///GO
        ///ALTER TABLE [dbo].[Tabla4] DROP CONSTRAINT [FK_Tabla4_Tabla1]
        ///GO
        ///ALTER TABLE [dbo].[Table7] DROP CONSTRAINT [FK_Table7_Tabla1]
        ///GO
        ///ALTER TABL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestConstraintFKTree1 {
            get {
                return ResourceManager.GetString("TestConstraintFKTree1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE TestIndexEnabled1
        ///GO
        ///
        ///DROP INDEX [IX_Tabla1_2] ON [dbo].[Tabla1]
        ///GO
        ///ALTER INDEX [IX_Tabla1_1] ON [dbo].[Tabla1] DISABLE
        ///GO
        ///ALTER INDEX [IX_Tabla1] ON [dbo].[Tabla1] REBUILD
        ///GO
        ///CREATE NONCLUSTERED INDEX [IX_Tabla1_2] ON [dbo].[Tabla1]
        ///(
        ///	[ID] ASC,
        ///	[Campo1] ASC
        ///) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ///GO
        ///CREATE NONCLUSTERED INDEX [IX3] ON [dbo].[Tabla1]
        ///(
        ///	[ID] ASC,
        ///	[Campo1] ASC,
        ///	[Campo2] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestIndexEnabled {
            get {
                return ResourceManager.GetString("TestIndexEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE TestIndexSimple1
        ///GO
        ///
        ///DROP INDEX [IX_Tabla1_Includes] ON [dbo].[Tabla1]
        ///GO
        ///DROP INDEX [IX_Table1_FillFactor] ON [dbo].[Tabla1]
        ///GO
        ///DROP INDEX [IX_Tabla1] ON [dbo].[Tabla1]
        ///GO
        ///DROP INDEX [IX_Sort_DB] ON [dbo].[Tabla1]
        ///GO
        ///CREATE NONCLUSTERED INDEX [IX DROP] ON [dbo].[Tabla1]
        ///(
        ///	[ID] ASC,
        ///	[ID2] ASC,
        ///	[ID3] ASC,
        ///	[ID4] ASC
        ///) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ///GO
        ///CREATE NONCLUSTERED INDEX [I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestIndexSimple {
            get {
                return ResourceManager.GetString("TestIndexSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE TestIndexUserType1
        ///GO
        ///
        ///DROP INDEX [IX3] ON [dbo].[Tabla1]
        ///GO
        ///DROP INDEX [IX2] ON [dbo].[Tabla1]
        ///GO
        ///DROP INDEX [IX1] ON [dbo].[Tabla1]
        ///GO
        ///ALTER TABLE [dbo].[Tabla1] ALTER COLUMN [ValorId] [int] NOT NULL
        ///GO
        ///ALTER TABLE [dbo].[Tabla1] ALTER COLUMN [Valor2Id] [money] NULL
        ///GO
        ///DROP TYPE [dbo].[Tipo1]
        ///GO
        ///CREATE TYPE [dbo].[Tipo1] FROM [int] NOT NULL
        ///GO
        ///DROP TYPE [dbo].[Tipo2]
        ///GO
        ///CREATE TYPE [dbo].[Tipo2] FROM [money] NOT NULL
        ///GO
        ///ALTER TABLE [dbo].[Tabla1] ALTER COLUMN [ValorId] [Tipo1] NOT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestIndexuserType {
            get {
                return ResourceManager.GetString("TestIndexuserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE TestIndexXML1
        ///GO
        ///
        ///CREATE NONCLUSTERED INDEX [IX_Tabla1] ON [dbo].[Tabla1]
        ///(
        ///	[ID] ASC
        ///) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ///GO
        ///CREATE PRIMARY XML INDEX [XML_IX_Tabla1] ON [dbo].[Tabla1]
        ///(
        ///	[Campo1]
        ///) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
        ///GO.
        /// </summary>
        internal static string TestIndexXML {
            get {
                return ResourceManager.GetString("TestIndexXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE TestSinonimos1
        ///GO
        ///
        ///DROP SYNONYM [dbo].[Tabla5]
        ///GO
        ///DROP SYNONYM [dbo].[Tabla2]
        ///GO
        ///CREATE SYNONYM [dbo].[Tabla4] FOR [TestSinonimos1].[dbo].[Tabla1]
        ///GO
        ///CREATE SYNONYM [dbo].[Tabla2] FOR [TestSinonimos1].[dbo].[Tabla3]
        ///GO.
        /// </summary>
        internal static string TestSynonyms {
            get {
                return ResourceManager.GetString("TestSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE TestViewComun1
        ///GO
        ///
        ///DROP VIEW [dbo].[Vista2]
        ///GO
        ///DROP VIEW [dbo].[Vista1]
        ///GO
        ///CREATE VIEW [dbo].[Vista3]
        ///AS
        ///SELECT     1 AS Test1, 2 AS Test2, 3 AS Test3
        ///
        ///GO
        ///CREATE VIEW dbo.Vista1
        ///AS
        ///SELECT     1 AS Test1, 2 AS Test2
        ///GO.
        /// </summary>
        internal static string TestViewComun {
            get {
                return ResourceManager.GetString("TestViewComun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE TestView1
        ///GO
        ///
        ///DROP VIEW [dbo].[Vista1]
        ///GO
        ///ALTER TABLE [dbo].[Tabla1] DROP CONSTRAINT [PK_Tabla1]
        ///GO
        ///CREATE TABLE [dbo].[Tabla2]
        ///(
        ///	[ID] [int] NOT NULL,
        ///	[Campo2] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
        ///	CONSTRAINT [PK_Tabla2] PRIMARY KEY CLUSTERED
        ///	(
        ///		[ID] ASC
        ///	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///GO
        ///CREATE TABLE [dbo].[TempTabla1]
        ///(
        ///	[ID] [int] IDENTITY ( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestViewSchemaBinding {
            get {
                return ResourceManager.GetString("TestViewSchemaBinding", resourceCulture);
            }
        }
    }
}
