//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace DBDiff.Schema.SQLServer.Generates.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("sa")]
        public string SQLServerUserOrigen {
            get {
                return ((string)(this["SQLServerUserOrigen"]));
            }
            set {
                this["SQLServerUserOrigen"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("sa")]
        public string SQLServerUserDestino {
            get {
                return ((string)(this["SQLServerUserDestino"]));
            }
            set {
                this["SQLServerUserDestino"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1")]
        public int SQLServerConnectionTypeOrigen {
            get {
                return ((int)(this["SQLServerConnectionTypeOrigen"]));
            }
            set {
                this["SQLServerConnectionTypeOrigen"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1")]
        public int SQLServerConnectionTypeDestino {
            get {
                return ((int)(this["SQLServerConnectionTypeDestino"]));
            }
            set {
                this["SQLServerConnectionTypeDestino"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string SQLServerNameOrigen {
            get {
                return ((string)(this["SQLServerNameOrigen"]));
            }
            set {
                this["SQLServerNameOrigen"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string SQLServerNameDestino {
            get {
                return ((string)(this["SQLServerNameDestino"]));
            }
            set {
                this["SQLServerNameDestino"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("-1")]
        public int SQLServerDatabaseOrigen {
            get {
                return ((int)(this["SQLServerDatabaseOrigen"]));
            }
            set {
                this["SQLServerDatabaseOrigen"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("-1")]
        public int SQLServerDatabaseDestino {
            get {
                return ((int)(this["SQLServerDatabaseDestino"]));
            }
            set {
                this["SQLServerDatabaseDestino"] = value;
            }
        }
    }
}
